export enum NOTIFICATION_TYPE {
  ORDER = 'ORDER',
  REFUND = 'REFUND',
}

export enum ORDER_ACTION_TYPE {
  ORDER_ORDER = 'ORDER_ORDER',
  ORDER_CANCEL = 'ORDER_CANCEL',
  ORDER_UPDATE_RECEIVER_INFO = 'ORDER_UPDATE_RECEIVER_INFO',
  ORDER_QUESTION = 'ORDER_QUESTION',
  ORDER_DELIVERY = 'ORDER_DELIVERY',
  ORDER_COMPLETE = 'ORDER_COMPLETE',
}

export enum REFUND_ACTION_TYPE {
  REFUND_REQUEST = 'REFUND_REQUEST',
  REFUND_COMPLETE = 'REFUND_COMPLETE',
}
